---
# Confirm whether to configure MacOS or not, some companies have policies against this.
- name: Confirm whether to configure MacOS or not, some companies have policies.
  pause:
    prompt: "Confirmation needed: Do you want to set up your Mac with sensible defaults? Some companies have policies with/against this (yes/no)"
  register: confirm_setup_mac
  when: ansible_facts["os_family"] == "Darwin"

# For MacOS, configure Mac's default settings.
- name: Configure MacOS default settings (if applicable)
  command: sh ../scripts/setup-macos.sh
  when: ansible_facts["os_family"] == "Darwin" and (confirm_setup_mac | bool)

# Prints out message.
- name: Finish setting up
  command: echo "Device has been successfully set up. Please reload the shell 👍"
