---
# Installs global packages. Need 'loop' because 'npm i' is unable to read something like: npm i [yarn, heroku] for example.
- name: Install global NPM packages
  npm:
    name: "{{ item }}"
    state: latest
    global: yes
  vars:
    packages:
      - yarn
  loop: "{{ packages }}"
