---
# Injects my aliases into '.zshrc'.
- name: Injects alias into '.zshrc' (if applicable)
  command: cp ../dotfiles/main.sh ~/.zshrc
  when: ansible_facts["os_family"] == "Darwin"

# Injects my aliases into '.bash_aliases'.
- name: Injects alias into '.bash_aliases' (if applicable)
  command: cp ../dotfiles/main.sh ~/.bash_aliases
  when: ansible_facts["distribution"] == "Ubuntu"

# Install fzf autocompletions.
- name: Install 'fzf' autocompletions
  shell: $(brew --prefix)/opt/fzf/install

# For MacOS, configure Mac's default settings.
- name: Configure MacOS default settings (if applicable)
  command: sh ../dotfiles/macos.sh
  when: ansible_facts["os_family"] == "Darwin"

# Prints out message.
- name: Finish setting up
  command: echo "Device has been successfully set up. Please reload the shell 👍"
