---
# Install `oh-my-zsh` for Shell.
- name: Install 'oh-my-zsh'
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh

# Install `fzf` autocompletions.
- name: Install 'fzf' autocompletions
  shell: $(brew --prefix)/opt/fzf/install

# Symlink aliases.
- name: Copy personal configuration to the user's home directory
  command: cp ../dotfiles/main.sh ~/.myconfig.zsh

# Finish everything by sourcing it from `.zshrc`.
- name: Source personal configuration dotfile by placing a small script
  command: echo "source $HOME/.myconfig.zsh" >> .zshrc
