---
# Install `oh-my-zsh` for Shell.
- name: Install 'oh-my-zsh'
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh

# Install `fzf` autocompletions.
- name: Install 'fzf' autocompletions
  shell: $(brew --prefix)/opt/fzf/install

# Finally, inject my aliases into '.zshrc'.
- name: Injects alias into '.zshrc' (if applicable)
  command: cp ../dotfiles/main.sh ~/.zshrc
